apiVersion: v1
kind: ConfigMap
metadata:
  name: mikrotik-config
data:
  DB_HOST: "mikrotik-db"
  DB_PORT: "5432"
  DB_NAME: "db_master_mikrotik"
  DB_USER: "postgres"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  POLLING_INTERVAL_MINUTES: "5"
  MAX_DB_CONNECTIONS: "20"
  ENABLE_SCHEDULER: "True"
