apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikrotik-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikrotik-redis
  template:
    metadata:
      labels:
        app: mikrotik-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: mikrotik-redis
