"""Add_Telegram_Models

Revision ID: 14e68ee19c92
Revises: b2dfec2d1b85
Create Date: 2026-02-28 16:11:22.648178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e68ee19c92'
down_revision: Union[str, Sequence[str], None] = 'b2dfec2d1b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_bots',
    sa.Column('bot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_name', sa.String(length=100), nullable=False),
    sa.Column('bot_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bot_id')
    )
    op.create_table('telegram_recipients',
    sa.Column('recipient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_levels', sa.ARRAY(sa.String()), server_default='{critical}', nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mikrotik_boards.board_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bot_id'], ['telegram_bots.bot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['master_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_recipients')
    op.drop_table('telegram_bots')
    # ### end Alembic commands ###
