"""add_automation_tables_v2

Revision ID: 3432abdce413
Revises: e5c12e4e244c
Create Date: 2026-02-28 23:28:10.568321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3432abdce413'
down_revision: Union[str, Sequence[str], None] = 'e5c12e4e244c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['master_users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('board_monthly_summary',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('avg_cpu_load', sa.Integer(), nullable=True),
    sa.Column('max_cpu_load', sa.Integer(), nullable=True),
    sa.Column('avg_download', sa.BigInteger(), nullable=True),
    sa.Column('max_download', sa.BigInteger(), nullable=True),
    sa.Column('total_download_bytes', sa.BigInteger(), nullable=True),
    sa.Column('avg_upload', sa.BigInteger(), nullable=True),
    sa.Column('max_upload', sa.BigInteger(), nullable=True),
    sa.Column('total_upload_bytes', sa.BigInteger(), nullable=True),
    sa.Column('avg_hotspot_users', sa.Integer(), nullable=True),
    sa.Column('max_hotspot_users', sa.Integer(), nullable=True),
    sa.Column('log_month', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mikrotik_boards.board_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index('idx_monthly_summary_board_date', 'board_monthly_summary', ['board_id', 'log_month'], unique=True)
    op.create_table('ztp_queue',
    sa.Column('ztp_id', sa.UUID(), nullable=False),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('identity', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('router_version', sa.String(length=50), nullable=True),
    sa.Column('temp_username', sa.String(length=50), nullable=True),
    sa.Column('temp_password', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['processed_by'], ['master_users.user_id'], ),
    sa.PrimaryKeyConstraint('ztp_id')
    )
    op.create_index('idx_ztp_status', 'ztp_queue', ['status'], unique=False)
    op.create_table('automation_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mikrotik_boards.board_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['automation_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.add_column('board_daily_summary', sa.Column('avg_cpu_load', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_cpu_load', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('min_free_memory', sa.BigInteger(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('total_download_bytes', sa.BigInteger(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_upload', sa.BigInteger(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('total_upload_bytes', sa.BigInteger(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('avg_hotspot_users', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_hotspot_users', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('avg_pppoe_users', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_pppoe_users', sa.Integer(), nullable=True))
    op.alter_column('board_daily_summary', 'avg_download',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('board_daily_summary', 'max_download',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('board_daily_summary', 'avg_upload',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_index('idx_daily_summary_board_date', 'board_daily_summary', ['board_id', 'log_date'], unique=True)
    op.drop_column('board_daily_summary', 'max_clients')
    op.create_index('idx_resource_stats_time', 'board_resource_stats', ['board_id', sa.literal_column('log_time DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_resource_stats_time', table_name='board_resource_stats')
    op.add_column('board_daily_summary', sa.Column('max_clients', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('idx_daily_summary_board_date', table_name='board_daily_summary')
    op.alter_column('board_daily_summary', 'avg_upload',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('board_daily_summary', 'max_download',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('board_daily_summary', 'avg_download',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('board_daily_summary', 'max_pppoe_users')
    op.drop_column('board_daily_summary', 'avg_pppoe_users')
    op.drop_column('board_daily_summary', 'max_hotspot_users')
    op.drop_column('board_daily_summary', 'avg_hotspot_users')
    op.drop_column('board_daily_summary', 'total_upload_bytes')
    op.drop_column('board_daily_summary', 'max_upload')
    op.drop_column('board_daily_summary', 'total_download_bytes')
    op.drop_column('board_daily_summary', 'min_free_memory')
    op.drop_column('board_daily_summary', 'max_cpu_load')
    op.drop_column('board_daily_summary', 'avg_cpu_load')
    op.drop_table('automation_logs')
    op.drop_index('idx_ztp_status', table_name='ztp_queue')
    op.drop_table('ztp_queue')
    op.drop_index('idx_monthly_summary_board_date', table_name='board_monthly_summary')
    op.drop_table('board_monthly_summary')
    op.drop_table('automation_jobs')
    # ### end Alembic commands ###
