"""add_audit_logs

Revision ID: 5b3ca2d94f79
Revises: 3432abdce413
Create Date: 2026-03-01 00:38:15.389105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3ca2d94f79'
down_revision: Union[str, Sequence[str], None] = '3432abdce413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_resource', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['master_users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_board_events_board_time', 'board_events', ['board_id', sa.literal_column('log_time DESC')], unique=False)
    op.create_index('idx_board_events_time', 'board_events', [sa.literal_column('log_time DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_board_events_time', table_name='board_events')
    op.drop_index('idx_board_events_board_time', table_name='board_events')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
