"""sync_schema

Revision ID: 03ba6b74d0e9
Revises: 7d5ef2a1b93c
Create Date: 2026-03-05 14:15:32.030136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03ba6b74d0e9'
down_revision: Union[str, Sequence[str], None] = '7d5ef2a1b93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_daily_board_sum'), 'board_daily_summary', type_='unique')
    op.create_index('idx_daily_summary_board_date', 'board_daily_summary', ['board_id', 'log_date'], unique=True)
    op.create_index('idx_board_events_time', 'board_events', [sa.literal_column('log_time DESC')], unique=False)
    op.drop_index(op.f('idx_active_interfaces'), table_name='board_interface_configs', postgresql_where='(is_active = true)')
    op.drop_constraint(op.f('unique_monthly_board_sum'), 'board_monthly_summary', type_='unique')
    op.create_index('idx_monthly_summary_board_date', 'board_monthly_summary', ['board_id', 'log_month'], unique=True)
    op.alter_column('master_users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('master_users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'teknisi'::character varying"))
    op.alter_column('master_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('master_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_board_access', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_board_access', 'board_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_board_access', 'granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_board_access', 'granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_board_access', 'board_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_board_access', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('master_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('master_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('master_users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'teknisi'::character varying"))
    op.alter_column('master_users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('idx_monthly_summary_board_date', table_name='board_monthly_summary')
    op.create_unique_constraint(op.f('unique_monthly_board_sum'), 'board_monthly_summary', ['board_id', 'log_month'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_active_interfaces'), 'board_interface_configs', ['board_id'], unique=False, postgresql_where='(is_active = true)')
    op.drop_index('idx_board_events_time', table_name='board_events')
    op.drop_index('idx_daily_summary_board_date', table_name='board_daily_summary')
    op.create_unique_constraint(op.f('unique_daily_board_sum'), 'board_daily_summary', ['board_id', 'log_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
