"""Add_analysis_indexes

Revision ID: 25fd1aae94b5
Revises: c0f515646a8d
Create Date: 2026-03-03 16:48:40.742048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25fd1aae94b5'
down_revision: Union[str, Sequence[str], None] = 'c0f515646a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_client_stats_brd_time', 'board_client_stats', ['board_id', 'log_time'], unique=False)
    op.drop_index(op.f('idx_usage_report'), table_name='board_interface_usage')
    op.create_index('idx_usage_report_v2', 'board_interface_usage', ['board_id', sa.literal_column('log_date DESC')], unique=False)
    op.drop_index(op.f('idx_pppoe_usage_lookup'), table_name='board_pppoe_usage')
    op.create_index('idx_pppoe_usage_lookup_v2', 'board_pppoe_usage', ['board_id', sa.literal_column('log_date DESC'), sa.literal_column('download_bytes DESC')], unique=False)
    op.create_index('idx_resource_stats_brd_time', 'board_resource_stats', ['board_id', 'log_time'], unique=False)
    op.create_index('idx_speed_brd_time', 'board_speed_stats', ['board_id', 'log_time'], unique=False)
    op.create_index('idx_hotspot_usage_lookup', 'hotspot_usage_raw', ['board_id', sa.literal_column('log_date DESC'), sa.literal_column('daily_download DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hotspot_usage_lookup', table_name='hotspot_usage_raw')
    op.drop_index('idx_speed_brd_time', table_name='board_speed_stats')
    op.drop_index('idx_resource_stats_brd_time', table_name='board_resource_stats')
    op.drop_index('idx_pppoe_usage_lookup_v2', table_name='board_pppoe_usage')
    op.create_index(op.f('idx_pppoe_usage_lookup'), 'board_pppoe_usage', [sa.literal_column('log_date DESC'), sa.literal_column('download_bytes DESC')], unique=False)
    op.drop_index('idx_usage_report_v2', table_name='board_interface_usage')
    op.create_index(op.f('idx_usage_report'), 'board_interface_usage', [sa.literal_column('log_date DESC'), 'board_id'], unique=False)
    op.drop_index('idx_client_stats_brd_time', table_name='board_client_stats')
    # ### end Alembic commands ###
