"""Add_UserBoardAccess_and_relationships

Revision ID: 335b32d43d15
Revises: 85a9c8928d0a
Create Date: 2026-02-28 19:55:29.780455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335b32d43d15'
down_revision: Union[str, Sequence[str], None] = '85a9c8928d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_board_access',
    sa.Column('access_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mikrotik_boards.board_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['master_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('access_id'),
    sa.UniqueConstraint('user_id', 'board_id', name='unique_access')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_board_access')
    # ### end Alembic commands ###
