"""add_composite_indexes_for_analysis

Revision ID: 356d59a65e84
Revises: 25fd1aae94b5
Create Date: 2026-03-03 16:54:21.970472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356d59a65e84'
down_revision: Union[str, Sequence[str], None] = '25fd1aae94b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
