"""Add_monthly_stats

Revision ID: 85a9c8928d0a
Revises: 14e68ee19c92
Create Date: 2026-02-28 16:54:34.703527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a9c8928d0a'
down_revision: Union[str, Sequence[str], None] = '14e68ee19c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_monthly_summary',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('avg_download', sa.Integer(), nullable=True),
    sa.Column('max_download', sa.Integer(), nullable=True),
    sa.Column('total_download_bytes', sa.Integer(), nullable=True),
    sa.Column('avg_upload', sa.Integer(), nullable=True),
    sa.Column('max_upload', sa.Integer(), nullable=True),
    sa.Column('total_upload_bytes', sa.Integer(), nullable=True),
    sa.Column('avg_cpu_load', sa.Integer(), nullable=True),
    sa.Column('max_cpu_load', sa.Integer(), nullable=True),
    sa.Column('avg_hotspot_users', sa.Integer(), nullable=True),
    sa.Column('max_hotspot_users', sa.Integer(), nullable=True),
    sa.Column('log_month', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mikrotik_boards.board_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.add_column('board_daily_summary', sa.Column('total_download_bytes', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_upload', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('total_upload_bytes', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('avg_cpu_load', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_cpu_load', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('min_free_memory', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('avg_hotspot_users', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_hotspot_users', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('avg_pppoe_users', sa.Integer(), nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_pppoe_users', sa.Integer(), nullable=True))
    op.drop_column('board_daily_summary', 'max_clients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_daily_summary', sa.Column('max_clients', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('board_daily_summary', 'max_pppoe_users')
    op.drop_column('board_daily_summary', 'avg_pppoe_users')
    op.drop_column('board_daily_summary', 'max_hotspot_users')
    op.drop_column('board_daily_summary', 'avg_hotspot_users')
    op.drop_column('board_daily_summary', 'min_free_memory')
    op.drop_column('board_daily_summary', 'max_cpu_load')
    op.drop_column('board_daily_summary', 'avg_cpu_load')
    op.drop_column('board_daily_summary', 'total_upload_bytes')
    op.drop_column('board_daily_summary', 'max_upload')
    op.drop_column('board_daily_summary', 'total_download_bytes')
    op.drop_table('board_monthly_summary')
    # ### end Alembic commands ###
