-- ============================================================
-- MIKROTIK MANAGEMENT SYSTEM - FULL DATABASE SCHEMA
-- Generated by: AI Assistant (Trae)
-- Date: 2026-03-05
-- Version: 2.2
-- Status: COMPLETE & SYNCHRONIZED (Single Source of Truth)
-- ============================================================

-- ============================================================
-- BAGIAN 0: INITIALIZATION & SETUP
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto"; -- Opsional untuk enkripsi di DB

-- ============================================================
-- NOMOR 1: MASTER USERS (Login & Access Management)
-- ============================================================
CREATE TABLE master_users (
    user_id       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username      VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL, 
    full_name     VARCHAR(100),
    role          VARCHAR(20) DEFAULT 'teknisi', -- admin, teknisi, viewer
    is_active     BOOLEAN DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- NOMOR 2: MIKROTIK BOARDS (CORE ASSET)
-- ============================================================
CREATE TABLE mikrotik_boards (
    board_id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- Identitas & Manajemen
    board_name        VARCHAR(100) NOT NULL,
    mikrotik_identity VARCHAR(100),
    board_model       VARCHAR(50),
    site_group        VARCHAR(50) DEFAULT 'Umum',
    
    -- Jaringan & Port
    mac_address       MACADDR NOT NULL,
    ip_address        INET NOT NULL,
    port_ssh          INT DEFAULT 22,
    port_api          INT DEFAULT 8728,
    port_winbox       INT DEFAULT 8291,
    port_ftp          INT DEFAULT 21,
    
    -- Status & Flags
    is_online         BOOLEAN DEFAULT FALSE,
    is_monitor        BOOLEAN DEFAULT TRUE,
    is_public_review  BOOLEAN DEFAULT TRUE,
    is_maintenance    BOOLEAN DEFAULT FALSE,
    
    -- Metadata
    last_ping_at      TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP 
);

CREATE INDEX idx_board_logic ON mikrotik_boards(is_online, is_monitor, is_public_review);
CREATE INDEX idx_board_site ON mikrotik_boards(site_group);

-- ============================================================
-- NOMOR 3: BOARD CREDENTIALS (Encrypted)
-- ============================================================
CREATE TABLE board_credentials (
    cred_id                     SERIAL PRIMARY KEY,
    board_id                    UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    username_mikrotik           VARCHAR(50) NOT NULL,
    password_mikrotik_encrypted TEXT NOT NULL, -- AES-256-GCM Encrypted
    updated_at                  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_board_credentials_board_id ON board_credentials(board_id);

-- ============================================================
-- NOMOR 4: USER BOARD ACCESS (RBAC)
-- ============================================================
CREATE TABLE user_board_access (
    access_id  SERIAL PRIMARY KEY,
    user_id    UUID REFERENCES master_users(user_id) ON DELETE CASCADE,
    board_id   UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    granted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_access UNIQUE(user_id, board_id)
);
CREATE INDEX idx_user_board_access_user_id ON user_board_access(user_id);
CREATE INDEX idx_user_board_access_board_id ON user_board_access(board_id);

-- ============================================================
-- NOMOR 5: VPN PROFILES
-- ============================================================
CREATE TABLE vpn_profiles (
    vpn_id                 SERIAL PRIMARY KEY,
    board_id               UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    
    vpn_type               VARCHAR(20) DEFAULT 'L2TP/IPSEC',
    vpn_api                VARCHAR(255),
    vpn_username           VARCHAR(50),
    vpn_password_encrypted TEXT,
    
    vpn_ssh                VARCHAR(255),
    vpn_ftp                VARCHAR(255),
    vpn_winbox             VARCHAR(255),
    
    is_connected           BOOLEAN DEFAULT FALSE,
    last_connected_at      TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_vpn_profiles_board_id ON vpn_profiles(board_id);

-- ============================================================
-- NOMOR 6: BOARD CLIENT STATS (Monitoring User)
-- ============================================================
CREATE TABLE board_client_stats (
    stat_id       BIGINT NOT NULL, -- Changed from BIGSERIAL for Partitioning Best Practice
    board_id      UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    total_hotspot INT DEFAULT 0,
    total_pppoe   INT DEFAULT 0,
    total_active  INT GENERATED ALWAYS AS (total_hotspot + total_pppoe) STORED,
    accuracy_pct  NUMERIC(5,2) DEFAULT 100.00, -- Metadata: Persentase akurasi data
    log_time      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (stat_id, log_time)
) PARTITION BY RANGE (log_time);
CREATE INDEX idx_client_stats_time ON board_client_stats(board_id, log_time DESC);

-- ============================================================
-- NOMOR 7: BOARD RESOURCE STATS (Health Check)
-- ============================================================
CREATE TABLE board_resource_stats (
    resource_id   BIGINT NOT NULL, -- Changed from BIGSERIAL
    board_id      UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    cpu_load      INT,             -- 0-100%
    free_memory   BIGINT,          -- Bytes
    free_hdd      BIGINT,          -- Bytes
    uptime        INTERVAL,
    accuracy_pct  NUMERIC(5,2) DEFAULT 100.00,
    log_time      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (resource_id, log_time)
) PARTITION BY RANGE (log_time);
CREATE INDEX idx_resource_stats_time ON board_resource_stats(board_id, log_time DESC);

-- ============================================================
-- NOMOR 8: BOARD SPEED STATS (Traffic)
-- ============================================================
CREATE TABLE board_speed_stats (
    speed_id       BIGINT NOT NULL, -- Changed from BIGSERIAL
    board_id       UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    interface_name VARCHAR(100) NOT NULL,
    download_mbps  NUMERIC(15,2) DEFAULT 0, -- Standardized to NUMERIC(15,2)
    upload_mbps    NUMERIC(15,2) DEFAULT 0, -- Standardized to NUMERIC(15,2)
    accuracy_pct   NUMERIC(5,2) DEFAULT 100.00,
    log_time       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (speed_id, log_time)
) PARTITION BY RANGE (log_time);
CREATE INDEX idx_speed_interface_time ON board_speed_stats(board_id, interface_name, log_time DESC);

-- ============================================================
-- NOMOR 9: BOARD DAILY SUMMARY (Aggregation)
-- ============================================================
CREATE TABLE board_daily_summary (
    summary_id           SERIAL PRIMARY KEY,
    board_id             UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    
    avg_download         NUMERIC(15,2), -- Standardized
    max_download         NUMERIC(15,2), -- Standardized
    total_download_bytes BIGINT DEFAULT 0,
    
    avg_upload           NUMERIC(15,2), -- Standardized
    max_upload           NUMERIC(15,2), -- Standardized
    total_upload_bytes   BIGINT DEFAULT 0,
    
    avg_cpu_load         INT DEFAULT 0,
    max_cpu_load         INT DEFAULT 0,
    min_free_memory      BIGINT DEFAULT 0,

    avg_hotspot_users    INT DEFAULT 0,
    max_hotspot_users    INT DEFAULT 0,
    
    avg_pppoe_users      INT DEFAULT 0,
    max_pppoe_users      INT DEFAULT 0,
    
    accuracy_pct         NUMERIC(5,2) DEFAULT 100.00, -- V2.1 Metadata Requirement
    log_date             DATE NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_daily_board_sum UNIQUE(board_id, log_date)
);
CREATE INDEX idx_board_daily_summary_lookup ON board_daily_summary(board_id, log_date DESC);

-- ============================================================
-- NOMOR 9a: BOARD INTERFACE DAILY SUMMARY (Aggregation per Port)
-- ============================================================
CREATE TABLE board_interface_daily_summary (
    summary_id           SERIAL PRIMARY KEY,
    board_id             UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    interface_name       VARCHAR(100) NOT NULL,
    
    avg_download_mbps    NUMERIC(15,2), -- Standardized
    max_download_mbps    NUMERIC(15,2), -- Standardized
    p95_download_mbps    NUMERIC(15,2), -- Standardized
    
    avg_upload_mbps      NUMERIC(15,2), -- Standardized
    max_upload_mbps      NUMERIC(15,2), -- Standardized
    
    accuracy_pct         NUMERIC(5,2) DEFAULT 100.00, -- V2.1 Metadata Requirement
    log_date             DATE NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_interface_daily UNIQUE(board_id, interface_name, log_date)
);
CREATE INDEX idx_interface_summary_lookup ON board_interface_daily_summary (board_id, interface_name, log_date DESC);

-- ============================================================
-- NOMOR 9b: BOARD MONTHLY SUMMARY (Aggregation)
-- ============================================================
CREATE TABLE board_monthly_summary (
    summary_id           SERIAL PRIMARY KEY,
    board_id             UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    
    avg_download         NUMERIC(15,2) DEFAULT 0, -- Standardized from BIGINT
    max_download         NUMERIC(15,2) DEFAULT 0, -- Standardized from BIGINT
    total_download_bytes BIGINT DEFAULT 0,
    
    avg_upload           NUMERIC(15,2) DEFAULT 0, -- Standardized from BIGINT
    max_upload           NUMERIC(15,2) DEFAULT 0, -- Standardized from BIGINT
    total_upload_bytes   BIGINT DEFAULT 0,
    
    avg_cpu_load         INT DEFAULT 0,
    max_cpu_load         INT DEFAULT 0,
    
    avg_hotspot_users    INT DEFAULT 0,
    max_hotspot_users    INT DEFAULT 0,

    accuracy_pct         NUMERIC(5,2) DEFAULT 100.00, -- V2.1 Metadata Requirement
    log_month            DATE NOT NULL, -- Tanggal 1 setiap bulan
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT unique_monthly_board_sum UNIQUE(board_id, log_month)
);
CREATE INDEX idx_board_monthly_summary_lookup ON board_monthly_summary(board_id, log_month DESC);

-- ============================================================
-- NOMOR 10: BOARD EVENTS (Audit Trail)
-- ============================================================
CREATE TABLE board_events (
    event_id       BIGINT NOT NULL, -- Changed from BIGSERIAL
    board_id       UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    event_category VARCHAR(20), -- connection, system, auth
    event_level    VARCHAR(10), -- info, warning, critical
    event_name     TEXT NOT NULL,
    event_detail   TEXT,
    performed_by   UUID REFERENCES master_users(user_id) ON DELETE SET NULL,
    is_reset_event BOOLEAN DEFAULT FALSE,
    accuracy_pct   NUMERIC(5,2) DEFAULT 100.00,
    log_time       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (event_id, log_time)
) PARTITION BY RANGE (log_time);
CREATE INDEX idx_board_events_board_time ON board_events(board_id, log_time DESC);

-- Trigger Otomatisasi Log Status
CREATE OR REPLACE FUNCTION fungsi_auto_log_status()
RETURNS TRIGGER AS $$
BEGIN
    IF (OLD.is_online != NEW.is_online) THEN
        INSERT INTO board_events (event_id, board_id, event_category, event_level, event_name, event_detail)
        VALUES (
            nextval('board_events_event_id_seq'), -- Explicitly handle sequence for partitioning
            NEW.board_id, 
            'connection', 
            CASE WHEN NEW.is_online THEN 'info' ELSE 'critical' END,
            CASE WHEN NEW.is_online THEN 'Router Connectivity Changed' ELSE 'Router Offline' END,
            CASE WHEN NEW.is_online THEN 'Router is now Online' ELSE 'Router Ping Timeout' END
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pencatat_status
AFTER UPDATE OF is_online ON mikrotik_boards
FOR EACH ROW EXECUTE PROCEDURE fungsi_auto_log_status();

-- ============================================================
-- NOMOR 11: BOARD BACKUPS
-- ============================================================
CREATE TABLE board_backups (
    backup_id      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    board_id       UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    log_date       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    file_name      VARCHAR(255) NOT NULL,
    router_name    VARCHAR(100),
    router_model   VARCHAR(50),
    file_location  TEXT NOT NULL,
    status         VARCHAR(20) DEFAULT 'success',
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_backup_board_history ON board_backups(board_id, log_date DESC);

-- ============================================================
-- NOMOR 12: TELEGRAM ALERT SYSTEM
-- ============================================================
CREATE TABLE telegram_bots (
    bot_id     SERIAL PRIMARY KEY,
    bot_name   VARCHAR(100) NOT NULL,
    bot_token  TEXT NOT NULL,
    is_active  BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE telegram_recipients (
    recipient_id SERIAL PRIMARY KEY,
    user_id      UUID REFERENCES master_users(user_id) ON DELETE CASCADE,
    bot_id       INT REFERENCES telegram_bots(bot_id) ON DELETE CASCADE,
    board_id     UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    chat_id      BIGINT NOT NULL,
    alert_levels TEXT[] DEFAULT '{critical}',
    is_active    BOOLEAN DEFAULT TRUE,
    CONSTRAINT unique_mapping UNIQUE(bot_id, board_id, chat_id)
);
CREATE INDEX idx_telegram_recipients_user_id ON telegram_recipients(user_id);
CREATE INDEX idx_telegram_recipients_board_id ON telegram_recipients(board_id);

-- ============================================================
-- NOMOR 13: INTERFACE CONFIGURATIONS
-- ============================================================
CREATE TABLE board_interface_configs (
    config_id         SERIAL PRIMARY KEY,
    board_id          UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    interface_name    VARCHAR(100) NOT NULL,
    interface_label   VARCHAR(100),
    is_active         BOOLEAN DEFAULT TRUE,
    is_primary_uplink BOOLEAN DEFAULT FALSE,
    created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_board_port UNIQUE(board_id, interface_name)
);
CREATE INDEX idx_active_interfaces ON board_interface_configs(board_id) WHERE is_active = TRUE;

-- ============================================================
-- NOMOR 14: INTERFACE TRAFFIC USAGE
-- ============================================================
CREATE TABLE board_interface_usage (
    usage_id       BIGINT NOT NULL, -- Changed from BIGSERIAL
    board_id       UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    interface_name VARCHAR(100) NOT NULL,
    total_tx_bytes BIGINT DEFAULT 0,
    total_rx_bytes BIGINT DEFAULT 0,
    accuracy_pct   NUMERIC(5,2) DEFAULT 100.00,
    log_date       DATE DEFAULT CURRENT_DATE,
    last_update    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (usage_id, log_date)
) PARTITION BY RANGE (log_date);
CREATE INDEX idx_usage_report ON board_interface_usage(board_id, log_date DESC);
CREATE INDEX idx_usage_interface_time ON board_interface_usage(board_id, interface_name, log_date DESC);

-- ============================================================
-- NOMOR 15: PPPOE USER USAGE
-- ============================================================
CREATE TABLE board_pppoe_usage (
    usage_id       BIGINT NOT NULL, -- Changed from BIGSERIAL
    board_id       UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    pppoe_username VARCHAR(100) NOT NULL,
    upload_bytes   BIGINT DEFAULT 0,
    download_bytes BIGINT DEFAULT 0,
    accuracy_pct   NUMERIC(5,2) DEFAULT 100.00,
    log_date       DATE DEFAULT CURRENT_DATE,
    last_update    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (usage_id, log_date)
) PARTITION BY RANGE (log_date);
CREATE INDEX idx_pppoe_usage_board_time ON board_pppoe_usage(board_id, log_date DESC);
CREATE INDEX idx_pppoe_usage_lookup ON board_pppoe_usage(board_id, pppoe_username, log_date DESC);

-- ============================================================
-- NOMOR 16: HOTSPOT USAGE
-- ============================================================
-- 16a. Raw Harian
CREATE TABLE hotspot_usage_raw (
    raw_id         BIGINT NOT NULL, -- Changed from BIGSERIAL
    board_id       UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    username       VARCHAR(100) NOT NULL,
    daily_download BIGINT DEFAULT 0,
    daily_upload   BIGINT DEFAULT 0,
    daily_uptime   BIGINT DEFAULT 0,
    accuracy_pct   NUMERIC(5,2) DEFAULT 100.00,
    log_date       DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (raw_id, log_date)
) PARTITION BY RANGE (log_date);
CREATE INDEX idx_hotspot_usage_board_time ON hotspot_usage_raw(board_id, log_date DESC);
CREATE INDEX idx_hotspot_usage_user_time ON hotspot_usage_raw(board_id, username, log_date DESC);

-- 16b. Bulanan (Summary)
CREATE TABLE hotspot_usage_monthly (
    summary_id       SERIAL PRIMARY KEY,
    username         VARCHAR(100) NOT NULL,
    total_download   BIGINT DEFAULT 0,
    total_upload     BIGINT DEFAULT 0,
    total_uptime     BIGINT DEFAULT 0,
    frequency_days   INT,
    month_period     DATE NOT NULL,
    is_frequent_user BOOLEAN DEFAULT FALSE,
    accuracy_pct     NUMERIC(5,2) DEFAULT 100.00, -- V2.1 Metadata Requirement
    last_updated     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_monthly UNIQUE(username, month_period)
);
CREATE INDEX idx_hotspot_usage_monthly_lookup ON hotspot_usage_monthly(username, month_period DESC);

-- ============================================================
-- PHASE 8: AUTOMATION (Mass Config & ZTP)
-- ============================================================
CREATE TABLE automation_jobs (
    job_id       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_type     VARCHAR(50) NOT NULL, -- mass_config, reboot
    payload      JSONB,
    description  TEXT,
    status       VARCHAR(20) DEFAULT 'pending', -- pending, running, completed
    created_by   UUID REFERENCES master_users(user_id),
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_automation_jobs_created_by ON automation_jobs(created_by);

CREATE TABLE automation_logs (
    log_id        BIGSERIAL PRIMARY KEY,
    job_id        UUID REFERENCES automation_jobs(job_id) ON DELETE CASCADE,
    board_id      UUID REFERENCES mikrotik_boards(board_id) ON DELETE CASCADE,
    status        VARCHAR(20) DEFAULT 'pending', -- pending, success, failed
    output        TEXT,
    error_message TEXT,
    executed_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_automation_logs_job_id ON automation_logs(job_id);
CREATE INDEX idx_automation_logs_board_id ON automation_logs(board_id);

CREATE TABLE ztp_queue (
    ztp_id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    mac_address    MACADDR NOT NULL,
    ip_address     INET NOT NULL,
    identity       VARCHAR(100),
    model          VARCHAR(50),
    router_version VARCHAR(50),
    temp_username  VARCHAR(50),
    temp_password  TEXT,
    status         VARCHAR(20) DEFAULT 'pending', -- pending, approved, rejected
    requested_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    processed_at   TIMESTAMP WITH TIME ZONE,
    processed_by   UUID REFERENCES master_users(user_id)
);
CREATE INDEX idx_ztp_status ON ztp_queue(status);
CREATE INDEX idx_ztp_mac_address ON ztp_queue(mac_address);

-- ============================================================
-- PHASE 14: AUDIT LOGS (Security & Compliance)
-- ============================================================
CREATE TABLE audit_logs (
    log_id          SERIAL PRIMARY KEY,
    user_id         UUID REFERENCES master_users(user_id) ON DELETE SET NULL,
    action          VARCHAR(50) NOT NULL, -- LOGIN, CREATE, UPDATE, DELETE
    target_resource VARCHAR(100) NOT NULL,
    details         JSONB,
    ip_address      VARCHAR(45),
    status          VARCHAR(20) DEFAULT 'SUCCESS',
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_details_gin ON audit_logs USING GIN (details); -- Optimized GIN Index
