"""sync_schema_vs_code_v2

Revision ID: e5c12e4e244c
Revises: 335b32d43d15
Create Date: 2026-02-28 20:09:52.169583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5c12e4e244c'
down_revision: Union[str, Sequence[str], None] = '335b32d43d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotspot_usage_monthly',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('total_download', sa.BigInteger(), nullable=True),
    sa.Column('total_upload', sa.BigInteger(), nullable=True),
    sa.Column('total_uptime', sa.BigInteger(), nullable=True),
    sa.Column('frequency_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_table('board_backups',
    sa.Column('backup_id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('log_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('router_name', sa.String(length=100), nullable=True),
    sa.Column('router_model', sa.String(length=50), nullable=True),
    sa.Column('file_location', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mikrotik_boards.board_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('backup_id')
    )
    op.create_index('idx_backup_board_history', 'board_backups', ['board_id', sa.literal_column('log_date DESC')], unique=False)
    op.create_table('board_interface_configs',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('interface_name', sa.String(length=100), nullable=False),
    sa.Column('interface_label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_primary_uplink', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mikrotik_boards.board_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('board_interface_usage',
    sa.Column('usage_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('interface_name', sa.String(length=100), nullable=False),
    sa.Column('total_tx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('total_rx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('log_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mikrotik_boards.board_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index('idx_usage_report', 'board_interface_usage', [sa.literal_column('log_date DESC'), 'board_id'], unique=False)
    op.create_table('board_pppoe_usage',
    sa.Column('usage_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('pppoe_username', sa.String(length=100), nullable=False),
    sa.Column('upload_bytes', sa.BigInteger(), nullable=True),
    sa.Column('download_bytes', sa.BigInteger(), nullable=True),
    sa.Column('log_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mikrotik_boards.board_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index('idx_pppoe_usage_lookup', 'board_pppoe_usage', [sa.literal_column('log_date DESC'), sa.literal_column('download_bytes DESC')], unique=False)
    op.create_table('hotspot_usage_raw',
    sa.Column('raw_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('daily_download', sa.BigInteger(), nullable=True),
    sa.Column('daily_upload', sa.BigInteger(), nullable=True),
    sa.Column('daily_uptime', sa.BigInteger(), nullable=True),
    sa.Column('log_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mikrotik_boards.board_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('raw_id')
    )
    op.drop_table('board_monthly_summary')
    op.add_column('board_client_stats', sa.Column('total_active', sa.Integer(), sa.Computed('total_hotspot + total_pppoe', persisted=True), nullable=True))
    op.alter_column('board_client_stats', 'stat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('board_credentials', 'password_mikrotik_encrypted',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('board_daily_summary', sa.Column('max_clients', sa.Integer(), nullable=True))
    op.alter_column('board_daily_summary', 'avg_download',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('board_daily_summary', 'max_download',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('board_daily_summary', 'avg_upload',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('board_daily_summary', 'log_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_column('board_daily_summary', 'max_pppoe_users')
    op.drop_column('board_daily_summary', 'max_hotspot_users')
    op.drop_column('board_daily_summary', 'avg_hotspot_users')
    op.drop_column('board_daily_summary', 'avg_cpu_load')
    op.drop_column('board_daily_summary', 'max_upload')
    op.drop_column('board_daily_summary', 'max_cpu_load')
    op.drop_column('board_daily_summary', 'total_download_bytes')
    op.drop_column('board_daily_summary', 'total_upload_bytes')
    op.drop_column('board_daily_summary', 'avg_pppoe_users')
    op.drop_column('board_daily_summary', 'min_free_memory')
    op.alter_column('board_events', 'event_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('board_events', 'event_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('board_events', 'event_detail',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('board_resource_stats', 'resource_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('board_resource_stats', 'free_memory',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('board_resource_stats', 'free_hdd',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('board_resource_stats', 'uptime',
               existing_type=sa.VARCHAR(),
               type_=sa.Interval(),
               existing_nullable=True,
               postgresql_using='uptime::interval')
    op.alter_column('board_speed_stats', 'speed_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('board_speed_stats', 'download_mbps',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('board_speed_stats', 'upload_mbps',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('telegram_bots', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('telegram_bots', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('telegram_bots', 'bot_token',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('telegram_recipients', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('telegram_recipients', 'alert_levels',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.ARRAY(sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{critical}'::character varying[]"))
    op.alter_column('vpn_profiles', 'vpn_password_encrypted',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vpn_profiles', 'vpn_password_encrypted',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('telegram_recipients', 'alert_levels',
               existing_type=postgresql.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True,
               existing_server_default=sa.text("'{critical}'::character varying[]"))
    op.drop_column('telegram_recipients', 'is_active')
    op.alter_column('telegram_bots', 'bot_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('telegram_bots', 'created_at')
    op.drop_column('telegram_bots', 'is_active')
    op.alter_column('board_speed_stats', 'upload_mbps',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('board_speed_stats', 'download_mbps',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('board_speed_stats', 'speed_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('board_resource_stats', 'uptime',
               existing_type=sa.Interval(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('board_resource_stats', 'free_hdd',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('board_resource_stats', 'free_memory',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('board_resource_stats', 'resource_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('board_events', 'event_detail',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('board_events', 'event_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('board_events', 'event_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('board_daily_summary', sa.Column('min_free_memory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('board_daily_summary', sa.Column('avg_pppoe_users', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('board_daily_summary', sa.Column('total_upload_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('board_daily_summary', sa.Column('total_download_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_cpu_load', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_upload', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('board_daily_summary', sa.Column('avg_cpu_load', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('board_daily_summary', sa.Column('avg_hotspot_users', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_hotspot_users', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('board_daily_summary', sa.Column('max_pppoe_users', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('board_daily_summary', 'log_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('board_daily_summary', 'avg_upload',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('board_daily_summary', 'max_download',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('board_daily_summary', 'avg_download',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('board_daily_summary', 'max_clients')
    op.alter_column('board_credentials', 'password_mikrotik_encrypted',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('board_client_stats', 'stat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('board_client_stats', 'total_active')
    op.create_table('board_monthly_summary',
    sa.Column('summary_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('avg_download', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_download', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_download_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_upload', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_upload', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_upload_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_cpu_load', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_cpu_load', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_hotspot_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_hotspot_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('log_month', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['mikrotik_boards.board_id'], name=op.f('board_monthly_summary_board_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id', name=op.f('board_monthly_summary_pkey'))
    )
    op.drop_table('hotspot_usage_raw')
    op.drop_index('idx_pppoe_usage_lookup', table_name='board_pppoe_usage')
    op.drop_table('board_pppoe_usage')
    op.drop_index('idx_usage_report', table_name='board_interface_usage')
    op.drop_table('board_interface_usage')
    op.drop_table('board_interface_configs')
    op.drop_index('idx_backup_board_history', table_name='board_backups')
    op.drop_table('board_backups')
    op.drop_table('hotspot_usage_monthly')
    # ### end Alembic commands ###
